---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "33"
year: "2018"
contributor: 
- "Karin Aleksander"
- "Christina Beckmann"
- "Ute Czerwinski"
- "Corinna Haas"
- "Jana Haase"
- "Max Hallmann"
- "Claudia Loest"
- "Iris Schewe"
- "Pamela Schmidt"
- "Katja Schöppe-Carstensen"
title: "Alltag in Berliner One-Person Libraries &mdash; ein kollektives Tagebuch"
urn: "urn:nbn:de:kobv:11-110-18452/20035-6"
date: 2018-04-22 10:00
comments: false
sharing: true
footer: true

---