---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "33"
year: "2018"
contributor: 
- "Karsten Schuldt"
title: "Einige Anmerkungen zur Stimmung des Personals am Arbeitsplatz Bibliothek"
urn: "urn:nbn:de:kobv:11-110-18452/20040-2"
date: 2018-05-04
comments: false
sharing: true
footer: true

---