---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "33"
year: "2018"
contributor: 
- "Birgit Christine Bittner"
title: "Was steckt hinter der Eule?"
subtitle: "Das Workshopangebot der Universitätsbibliothek der Technisches Universität Wien im Rahmen der KinderuniTechnik Wien"
urn: "urn:nbn:de:kobv:11-110-18452/20038-4"
date: 2018-05-04
comments: false
sharing: true
footer: true

---