---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "33"
year: "2018"
contributor: 
- "Ben Kaden"
title: "Warum Forschungsdaten nicht publiziert werden"
urn: "urn:nbn:de:kobv:11-110-18452/20046-8"
date: 2018-05-04
comments: false
sharing: true
footer: true

---