---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "33"
year: "2018"
contributor: 
- "Kerstin Bieber"
- "Roswitha Brabandt"
- "Rebecca Krentz"
- "Sabine Schuhknecht"
- "Ute Stelzner"
- "Katja Werner"
title: "Bibliothek der Hochschule für Technik und Wirtschaft (HTW) Dresden"
urn: "urn:nbn:de:kobv:11-110-18452/20042-4"
date: 2018-04-28
comments: false
sharing: true
footer: true

---
