---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "33"
year: "2018"
contributor: 
- "Verena Burtscher"
- "Bibliotheksmitarbeiterinnen im Jugendteam der Walserbibliothek Raggal (Franziska, Julia, Helena, Viktoria, Janine, Nina, Luisa, Leonie, Leonora, Mia)"
title: "Jugendteam &mdash; Partizipationsmöglichkeit Jugendlicher in öffentlichen Bibliotheken"
urn: "urn:nbn:de:kobv:11-110-18452/20036-2"
date: 2018-05-14 22:00
comments: false
sharing: true
footer: true

---