---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "33"
year: "2018"
contributor: 
- "Rosa Helena Cunha Vidal"
title: "Goethe-Institut Porto Alegre"
pdf: "../master.pdf"
date: 2018-04-29
comments: false
sharing: true
footer: true

---