---

layout: page
lang: "en"
journal: "LIBREAS. Library Ideas"
issue: "33"
year: "2018"
contributor: 
- "Karen Bordonaro"
- "Shelby Angalik"
title: "Libraries and the Arctic: Language Education Support"
urn: "urn:nbn:de:kobv:11-110-18452/20045-2"
date: 2018-05-04
comments: false
sharing: true
footer: true

---