---

layout: page
lang: "de"
journal: "LIBREAS. Library Ideas"
issue: "33"
year: "2018"
contributor: 
- "Bernhard Mittermaier"
- "Christoph Holzke"
- "Claudia Frick"
- "Irene Barbers"
title: "Open Access löst nicht alle Probleme – aber mehr, als mancher meint"
subtitle: "Eine Replik zu: „Die Transformation des Publikationssystems zu Open Access und die Konsequenzen für Bibliotheken und Wissenschaft: Ausgewählte Aspekte.“"
pdf: "master.pdf"
date: 2018-04-21
comments: false
sharing: true
footer: true

---